openapi: 3.0.3
info:
  title: Camping API
  version: 1.1.0
  contact: {}
servers:
  - url: 'http://localhost:8080/api'
paths:
  /user/{userId}:
    get:
      tags:
        - User
      summary: GET User by UID
      description: Get User from Camping DB using firebase registered user UID
      operationId: getUserById
      parameters:
        - name: userId
          required: true
          in: path
          schema:
            type: string
            example: RgYM60evCyfBxbYmxWg7o0Pqhpz2
      responses:
        '500':
          description: Internal Server Error
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /user/:
    patch:
      tags:
        - User
      summary: Update User Profile
      description: Update User profile to tell about yourself for other teammates
      operationId: updateUserProfile
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                fullname: 
                  type: string
                  example: Genious
                bio:
                  type: string
                  example: >-
                    full enthusiasm, well-motivated person and ready to constructive communication
                occupation:
                  type: string
                  example: Web developer
                uid:
                  type: string
                  example: RgYM60evCyfBxbYmxWg7o0Pqhpz2
            example:
              fullname: Genious
              bio: >-
                full enthusiasm, well-motivated person and ready to constructive communication
              occupation: Web developer
              uid: RgYM60evCyfBxbYmxWg7o0Pqhpz2
      responses:
        '500':
          description: Internal Server Error
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: 
                    type: string
                    example: User profile updated successfully
  /user/avatar:
    patch:
      tags:
        - User
      summary: Update User Avatar
      description: Update User avatar image as base64 format
      operationId: updateUserAvatar
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                avatar:
                  type: string
                  example: >-
                    data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAl/SURBVHgB1Zt/bBTHFce/s3tnbJ+Nj/oHxaXNYWhQgohNbCN+RLKRU6VN0oIKaaK6LUZq/mijClo1SipVst30j6KmBaRGTdo/sKWgVjW0RoFGbYm4SCUmmBYnFCTUBkzS4ILt+MA+Y+7X9L29H947751373Yd8kHL7u3Nzs17897Mm7djAYcZuT3gc7vVVilEvZDwCQEfIL1SCp++nBBymP4PSIlhKWPvCKEOhcPhoWUlG4fhIAIOMBoebIWCrQrktkxBrSIghqWAX8Zkb7W72Q+bsU0BV+Q57+JYZDck9kjACwdgZUQR646Go367LKNgBSyE4JlQowP0X08oFDlQqCIKUsB49AwJLroWSvBMkhZR41rfgzzJSwHxgc11kC5bcRfAigiFw1vysQbLCnCi1yeC/8OF/55CgM4zoSl4PZ9G3dJ61NU0WKkmIGPR7uqiDfutPGRJAePRwX00Te2x8sxMeAoXPvg7rtx4RxOUWbZkFTav3o6SojL0DezFxQ9PGT67hBTRuOIRtK3dCbPQNNtVqTZ3my5vtuB45OxBCdkBC5y6dAQnzvdqSjCCBUwqJReb792OxxufgXlET5WraZepkmYKUc+fo563ZI9v/KtXE94uHiKLuTbxH01h7BpsFazAbJAlDJElrJuv3nkVkE/PX74xhN++8QM4CQv/dNsvcyrBjCUoub6knu+0Kjzzj8t/gdOwJRw+vXeeUrKDx61cJbIqgEd7MvsuWIT9fYRMdSG4TANrtvElCQ/ao6HTWQduQwXwPM9THSzCvbL36NcxEngPC8XE1PyDqFDUTk0mAwwVUFSknsxnns814n/MeBOB2xzmKOBG5ExHviu4gIkpzU54AOSYwiStRq6QpgA2E1WgE3lSTIHNQtK29luWyrMrTNDiTX8vTQFFRa7dhazf71++GQtBsbsMjz/4DEWJX4RFvJFIKM0KUnFAYoFzDgXG+Mf++ZIWATrBvWX3Y3X5fWhubIe7PO9mBlTVtWKJWBfgD67kXZXSVrBhgcM9wz3EkeB8VBZVYzUJpafEVYpS1UNHaer6syU+KluVKnOLvgsjb5JW0MUfZhVAvk9zpi3kjs5m6fB9Z44C5kAxLexqWKpKZTcSCtDGAM7hFZq701P7qZVpn9tqvqQJu6myJe3++J1Rfatmj9mbceFFesQuogUrxKvlLZGwACEErTft0/Iy7yrNDTgmeHL5TrQtfVSrflNlK5lyDV4b6ZstrPVwRgWZSsi4J2xoqqCELZ38SrzuWCtsJjkjbKxqSf6ixpdrnyBr+C4aKpqxevGaxHciUUBkba7dCEXZqp0To/8V2ExyRfibxj8YF8jHt1kP9MhkbTlCZYtQKKqq+hS3221pnW+W2oQbXJq6aFwg07fn+D9mPyfPCX1JNeci1jThcGSLImXUEQVwVNhY9wgGxv3pA1zmYJcmuEx4gpgrfNpz9riEItCg0JRQD4fgceCtMT8uTV7I+CabEArMCCcVexRAuQ6fEn9X5wycuqqrqccvLnWhZ/il9GlPQ2Qc+vuJs5hbJmaTAhRFuUfhF5VwkPuWP6Sd2RLeYnfQC2ooh7Hf67+Pue0ZA6gur2JnAGREE6W1GQ5pN1W1zvVl7Rq6+9D5PXTfxa+jxS7YhZTSZ19tWeDB8IHqjdhWsx2Vi5ZmKZXF/A3K2GX+qVrHIoP2BtoGlN2YxqJbIRhHmwI5o9BUpBgvE6wqxYy38BggieMWkEKT02Skl9SJXjcJRURK7G2yEt+ZsUCIXIdInwxExjMED36RRSrsgtZAwwpvS4HTiCxSh+9QWpemxtCdZMGcR7CqBPYiAy7ek0NXjkSDaaSmNZ2/u4sBD52vv0/OWETZEMoplpTG7yuzU12YzH6mogghjxt2EovFrrqoQVfnxOB2IzHr0xDpLr+IerW2Lq6EW+PAzXHtdmhZDYKrPkdxv7At8jNgSKHGDMFpjHxbj4t69jOURPFS2svt1srE+B/5vIPCg3eiucLhqJ+Ww3Ce+QQhE6moBsorgelJCiCcbxNvw1N4W4nTM4EaMRNqJBTEvl9WAbW4Ak7C22pYdm2kkTEchUOw8K6ZGLIuiY3CYDrctyMmFZcfvPeQz3EFQPTDAViAxSO35ymldw3dIoeUwM86pQTeeJn26xQST8CmjU/nL7yLgbMD+OiDa/h5+7NZSmWGwEYhscAr/j68f/sjbHt0K+p8K2EHbP6VrqYV8esEo+G3uyg5kvd7weB0EH/z/xUDg6dx/uK7qftPbX4M3//KLmtJ54Qu9r12EL8/dTx1e2n1UrTvaMfaNQ9o1/kSg9yV3FuYUgC/NIxGI5wctWQFLHj/8X70v/4nBINBwzLLllTj2w8/iZY161HOgU4y35/WgjiTM9M4PniSBD+GkYlRw/o8Hg82Nm1C+xPt+SgiQLnAdck9hWk/b8UKWPBXel7GiTdPwAoP1q3B52tXoLy4FLVLarR7kzNBXCNh/33tCh3D2mezPNzyBWuKkOJAlbsp9YI0TQFmreBQ36GcPf5x0L7jG5oicmG0o3ROdDIaGtwjFBhuLLo+eh0vvPgCLg8v3BYYK7AV/Kxzb1Zr0Pt+EsPwjGaEk8jYB/weCf38T567q3rdCB4fWAkr70mfMfQjvx7D7CINEjRsI7VM5p7/KfW83cK/+qIfv+62NwThNj7f/ZzW5iTUywE2faPyhgpgH6HosDv5+VDfq2kV2sXvjr2MN8+8DrthJRz986xiYyRLtp3kOVcoY+Gz+4PTU7s7vrfzrjf9TNgVen7Vi9IST3e1u7krW7mcCXaeLmiO7/2kCc9wm/9Ibc8lPGNqsb1+exXvHbI9a/T0155FmacC+w7+GA4wdObI2LybpU29YuGKaMHUC5sp83jt3JeRgttqRnjGUrpl/Y6qLqo97/XCQkDCHxg8Mmr6jzos5Zg/vDjtX76m+CZ12gaaV4txF0FvegOU4/8R9XyXlefySrht2Ob1xRT1JK3ZfSiAx1qfwtT0zYKnQuoQvxqN7DrdHxiGRQrKODZ/tbKDKujMVxEcCFHP4Zs/3JLP48le73778JilP5TSU3DKla0hqqrsczvJLSwtpcs9i7XzZPCWlcc0wemtzoHSSGS/vz9Q0Isd23LOmiIUtbUQi5gPOwVP4kjSvWlHVasiZQe1uKVgZUhBWevY0agQ/WcPj/lhM44oQA9bRlhVG1QpGiBkPf2kj4Ty0rUvrSAJSveoV+UwNepqTCpDaizsz2dgs8L/AY4Kgo8iJUfVAAAAAElFTkSuQmCC
                uid:
                  type: string
                  example: RgYM60evCyfBxbYmxWg7o0Pqhpz2
            example:
              avatar: >-
                data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAl/SURBVHgB1Zt/bBTHFce/s3tnbJ+Nj/oHxaXNYWhQgohNbCN+RLKRU6VN0oIKaaK6LUZq/mijClo1SipVst30j6KmBaRGTdo/sKWgVjW0RoFGbYm4SCUmmBYnFCTUBkzS4ILt+MA+Y+7X9L29H947751373Yd8kHL7u3Nzs17897Mm7djAYcZuT3gc7vVVilEvZDwCQEfIL1SCp++nBBymP4PSIlhKWPvCKEOhcPhoWUlG4fhIAIOMBoebIWCrQrktkxBrSIghqWAX8Zkb7W72Q+bsU0BV+Q57+JYZDck9kjACwdgZUQR646Go367LKNgBSyE4JlQowP0X08oFDlQqCIKUsB49AwJLroWSvBMkhZR41rfgzzJSwHxgc11kC5bcRfAigiFw1vysQbLCnCi1yeC/8OF/55CgM4zoSl4PZ9G3dJ61NU0WKkmIGPR7uqiDfutPGRJAePRwX00Te2x8sxMeAoXPvg7rtx4RxOUWbZkFTav3o6SojL0DezFxQ9PGT67hBTRuOIRtK3dCbPQNNtVqTZ3my5vtuB45OxBCdkBC5y6dAQnzvdqSjCCBUwqJReb792OxxufgXlET5WraZepkmYKUc+fo563ZI9v/KtXE94uHiKLuTbxH01h7BpsFazAbJAlDJElrJuv3nkVkE/PX74xhN++8QM4CQv/dNsvcyrBjCUoub6knu+0Kjzzj8t/gdOwJRw+vXeeUrKDx61cJbIqgEd7MvsuWIT9fYRMdSG4TANrtvElCQ/ao6HTWQduQwXwPM9THSzCvbL36NcxEngPC8XE1PyDqFDUTk0mAwwVUFSknsxnns814n/MeBOB2xzmKOBG5ExHviu4gIkpzU54AOSYwiStRq6QpgA2E1WgE3lSTIHNQtK29luWyrMrTNDiTX8vTQFFRa7dhazf71++GQtBsbsMjz/4DEWJX4RFvJFIKM0KUnFAYoFzDgXG+Mf++ZIWATrBvWX3Y3X5fWhubIe7PO9mBlTVtWKJWBfgD67kXZXSVrBhgcM9wz3EkeB8VBZVYzUJpafEVYpS1UNHaer6syU+KluVKnOLvgsjb5JW0MUfZhVAvk9zpi3kjs5m6fB9Z44C5kAxLexqWKpKZTcSCtDGAM7hFZq701P7qZVpn9tqvqQJu6myJe3++J1Rfatmj9mbceFFesQuogUrxKvlLZGwACEErTft0/Iy7yrNDTgmeHL5TrQtfVSrflNlK5lyDV4b6ZstrPVwRgWZSsi4J2xoqqCELZ38SrzuWCtsJjkjbKxqSf6ixpdrnyBr+C4aKpqxevGaxHciUUBkba7dCEXZqp0To/8V2ExyRfibxj8YF8jHt1kP9MhkbTlCZYtQKKqq+hS3221pnW+W2oQbXJq6aFwg07fn+D9mPyfPCX1JNeci1jThcGSLImXUEQVwVNhY9wgGxv3pA1zmYJcmuEx4gpgrfNpz9riEItCg0JRQD4fgceCtMT8uTV7I+CabEArMCCcVexRAuQ6fEn9X5wycuqqrqccvLnWhZ/il9GlPQ2Qc+vuJs5hbJmaTAhRFuUfhF5VwkPuWP6Sd2RLeYnfQC2ooh7Hf67+Pue0ZA6gur2JnAGREE6W1GQ5pN1W1zvVl7Rq6+9D5PXTfxa+jxS7YhZTSZ19tWeDB8IHqjdhWsx2Vi5ZmKZXF/A3K2GX+qVrHIoP2BtoGlN2YxqJbIRhHmwI5o9BUpBgvE6wqxYy38BggieMWkEKT02Skl9SJXjcJRURK7G2yEt+ZsUCIXIdInwxExjMED36RRSrsgtZAwwpvS4HTiCxSh+9QWpemxtCdZMGcR7CqBPYiAy7ek0NXjkSDaaSmNZ2/u4sBD52vv0/OWETZEMoplpTG7yuzU12YzH6mogghjxt2EovFrrqoQVfnxOB2IzHr0xDpLr+IerW2Lq6EW+PAzXHtdmhZDYKrPkdxv7At8jNgSKHGDMFpjHxbj4t69jOURPFS2svt1srE+B/5vIPCg3eiucLhqJ+Ww3Ce+QQhE6moBsorgelJCiCcbxNvw1N4W4nTM4EaMRNqJBTEvl9WAbW4Ak7C22pYdm2kkTEchUOw8K6ZGLIuiY3CYDrctyMmFZcfvPeQz3EFQPTDAViAxSO35ymldw3dIoeUwM86pQTeeJn26xQST8CmjU/nL7yLgbMD+OiDa/h5+7NZSmWGwEYhscAr/j68f/sjbHt0K+p8K2EHbP6VrqYV8esEo+G3uyg5kvd7weB0EH/z/xUDg6dx/uK7qftPbX4M3//KLmtJ54Qu9r12EL8/dTx1e2n1UrTvaMfaNQ9o1/kSg9yV3FuYUgC/NIxGI5wctWQFLHj/8X70v/4nBINBwzLLllTj2w8/iZY161HOgU4y35/WgjiTM9M4PniSBD+GkYlRw/o8Hg82Nm1C+xPt+SgiQLnAdck9hWk/b8UKWPBXel7GiTdPwAoP1q3B52tXoLy4FLVLarR7kzNBXCNh/33tCh3D2mezPNzyBWuKkOJAlbsp9YI0TQFmreBQ36GcPf5x0L7jG5oicmG0o3ROdDIaGtwjFBhuLLo+eh0vvPgCLg8v3BYYK7AV/Kxzb1Zr0Pt+EsPwjGaEk8jYB/weCf38T567q3rdCB4fWAkr70mfMfQjvx7D7CINEjRsI7VM5p7/KfW83cK/+qIfv+62NwThNj7f/ZzW5iTUywE2faPyhgpgH6HosDv5+VDfq2kV2sXvjr2MN8+8DrthJRz986xiYyRLtp3kOVcoY+Gz+4PTU7s7vrfzrjf9TNgVen7Vi9IST3e1u7krW7mcCXaeLmiO7/2kCc9wm/9Ibc8lPGNqsb1+exXvHbI9a/T0155FmacC+w7+GA4wdObI2LybpU29YuGKaMHUC5sp83jt3JeRgttqRnjGUrpl/Y6qLqo97/XCQkDCHxg8Mmr6jzos5Zg/vDjtX76m+CZ12gaaV4txF0FvegOU4/8R9XyXlefySrht2Ob1xRT1JK3ZfSiAx1qfwtT0zYKnQuoQvxqN7DrdHxiGRQrKODZ/tbKDKujMVxEcCFHP4Zs/3JLP48le73778JilP5TSU3DKla0hqqrsczvJLSwtpcs9i7XzZPCWlcc0wemtzoHSSGS/vz9Q0Isd23LOmiIUtbUQi5gPOwVP4kjSvWlHVasiZQe1uKVgZUhBWevY0agQ/WcPj/lhM44oQA9bRlhVG1QpGiBkPf2kj4Ty0rUvrSAJSveoV+UwNepqTCpDaizsz2dgs8L/AY4Kgo8iJUfVAAAAAElFTkSuQmCC
              uid: RgYM60evCyfBxbYmxWg7o0Pqhpz2
      responses:
        '500':
          description: Internal Server Error
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: 
                    type: string
                    example: User avatar was changed
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: 
                    type: string
                    example: Avatar format is not allowed or incorrect. Use base64 instead
  /trip/bag/all/{userId}:
    get:
      tags:
        - Bag
      summary: Get bag items
      description: Get bag items of activated trip 
      operationId: getBagItems
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
            example: RgYM60evCyfBxbYmxWg7o0Pqhpz2
      responses:
        '500':
          description: Internal Server Error
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: array
                items: 
                  "$ref": '#/components/schemas/Bag'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: 
                    type: string
                    example: User has no activated trip
  /trip/bag/{tripId}:
    post:
      tags:
        - Bag
      summary: Add bag item
      description: Add bag item into trip 
      operationId: addBagItem
      parameters:
        - in: path
          name: tripId
          required: true
          schema:
            type: string
            example: 63c93dbe37daeff8aa65cc98
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                  example: Camera
                userId:
                  type: string
                  example: RgYM60evCyfBxbYmxWg7o0Pqhpz2
            example:
              description: Camera
              userId: RgYM60evCyfBxbYmxWg7o0Pqhpz2
      responses:
        '500':
          description: Internal Server Error
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: 
                    type: string
                    example: Bag item added successfully
  /trip/bag/image:
    patch:
      tags:
        - Bag
      summary: Update bag image
      description: Update bag item image as base64 format
      operationId: updateBagImage
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                bagItemId:
                  type: string
                  example: 205c24f86d4b8c79201f5d4d26c7d3c4
                image:
                  type: string
                  example: >-
                    data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAl/SURBVHgB1Zt/bBTHFce/s3tnbJ+Nj/oHxaXNYWhQgohNbCN+RLKRU6VN0oIKaaK6LUZq/mijClo1SipVst30j6KmBaRGTdo/sKWgVjW0RoFGbYm4SCUmmBYnFCTUBkzS4ILt+MA+Y+7X9L29H947751373Yd8kHL7u3Nzs17897Mm7djAYcZuT3gc7vVVilEvZDwCQEfIL1SCp++nBBymP4PSIlhKWPvCKEOhcPhoWUlG4fhIAIOMBoebIWCrQrktkxBrSIghqWAX8Zkb7W72Q+bsU0BV+Q57+JYZDck9kjACwdgZUQR646Go367LKNgBSyE4JlQowP0X08oFDlQqCIKUsB49AwJLroWSvBMkhZR41rfgzzJSwHxgc11kC5bcRfAigiFw1vysQbLCnCi1yeC/8OF/55CgM4zoSl4PZ9G3dJ61NU0WKkmIGPR7uqiDfutPGRJAePRwX00Te2x8sxMeAoXPvg7rtx4RxOUWbZkFTav3o6SojL0DezFxQ9PGT67hBTRuOIRtK3dCbPQNNtVqTZ3my5vtuB45OxBCdkBC5y6dAQnzvdqSjCCBUwqJReb792OxxufgXlET5WraZepkmYKUc+fo563ZI9v/KtXE94uHiKLuTbxH01h7BpsFazAbJAlDJElrJuv3nkVkE/PX74xhN++8QM4CQv/dNsvcyrBjCUoub6knu+0Kjzzj8t/gdOwJRw+vXeeUrKDx61cJbIqgEd7MvsuWIT9fYRMdSG4TANrtvElCQ/ao6HTWQduQwXwPM9THSzCvbL36NcxEngPC8XE1PyDqFDUTk0mAwwVUFSknsxnns814n/MeBOB2xzmKOBG5ExHviu4gIkpzU54AOSYwiStRq6QpgA2E1WgE3lSTIHNQtK29luWyrMrTNDiTX8vTQFFRa7dhazf71++GQtBsbsMjz/4DEWJX4RFvJFIKM0KUnFAYoFzDgXG+Mf++ZIWATrBvWX3Y3X5fWhubIe7PO9mBlTVtWKJWBfgD67kXZXSVrBhgcM9wz3EkeB8VBZVYzUJpafEVYpS1UNHaer6syU+KluVKnOLvgsjb5JW0MUfZhVAvk9zpi3kjs5m6fB9Z44C5kAxLexqWKpKZTcSCtDGAM7hFZq701P7qZVpn9tqvqQJu6myJe3++J1Rfatmj9mbceFFesQuogUrxKvlLZGwACEErTft0/Iy7yrNDTgmeHL5TrQtfVSrflNlK5lyDV4b6ZstrPVwRgWZSsi4J2xoqqCELZ38SrzuWCtsJjkjbKxqSf6ixpdrnyBr+C4aKpqxevGaxHciUUBkba7dCEXZqp0To/8V2ExyRfibxj8YF8jHt1kP9MhkbTlCZYtQKKqq+hS3221pnW+W2oQbXJq6aFwg07fn+D9mPyfPCX1JNeci1jThcGSLImXUEQVwVNhY9wgGxv3pA1zmYJcmuEx4gpgrfNpz9riEItCg0JRQD4fgceCtMT8uTV7I+CabEArMCCcVexRAuQ6fEn9X5wycuqqrqccvLnWhZ/il9GlPQ2Qc+vuJs5hbJmaTAhRFuUfhF5VwkPuWP6Sd2RLeYnfQC2ooh7Hf67+Pue0ZA6gur2JnAGREE6W1GQ5pN1W1zvVl7Rq6+9D5PXTfxa+jxS7YhZTSZ19tWeDB8IHqjdhWsx2Vi5ZmKZXF/A3K2GX+qVrHIoP2BtoGlN2YxqJbIRhHmwI5o9BUpBgvE6wqxYy38BggieMWkEKT02Skl9SJXjcJRURK7G2yEt+ZsUCIXIdInwxExjMED36RRSrsgtZAwwpvS4HTiCxSh+9QWpemxtCdZMGcR7CqBPYiAy7ek0NXjkSDaaSmNZ2/u4sBD52vv0/OWETZEMoplpTG7yuzU12YzH6mogghjxt2EovFrrqoQVfnxOB2IzHr0xDpLr+IerW2Lq6EW+PAzXHtdmhZDYKrPkdxv7At8jNgSKHGDMFpjHxbj4t69jOURPFS2svt1srE+B/5vIPCg3eiucLhqJ+Ww3Ce+QQhE6moBsorgelJCiCcbxNvw1N4W4nTM4EaMRNqJBTEvl9WAbW4Ak7C22pYdm2kkTEchUOw8K6ZGLIuiY3CYDrctyMmFZcfvPeQz3EFQPTDAViAxSO35ymldw3dIoeUwM86pQTeeJn26xQST8CmjU/nL7yLgbMD+OiDa/h5+7NZSmWGwEYhscAr/j68f/sjbHt0K+p8K2EHbP6VrqYV8esEo+G3uyg5kvd7weB0EH/z/xUDg6dx/uK7qftPbX4M3//KLmtJ54Qu9r12EL8/dTx1e2n1UrTvaMfaNQ9o1/kSg9yV3FuYUgC/NIxGI5wctWQFLHj/8X70v/4nBINBwzLLllTj2w8/iZY161HOgU4y35/WgjiTM9M4PniSBD+GkYlRw/o8Hg82Nm1C+xPt+SgiQLnAdck9hWk/b8UKWPBXel7GiTdPwAoP1q3B52tXoLy4FLVLarR7kzNBXCNh/33tCh3D2mezPNzyBWuKkOJAlbsp9YI0TQFmreBQ36GcPf5x0L7jG5oicmG0o3ROdDIaGtwjFBhuLLo+eh0vvPgCLg8v3BYYK7AV/Kxzb1Zr0Pt+EsPwjGaEk8jYB/weCf38T567q3rdCB4fWAkr70mfMfQjvx7D7CINEjRsI7VM5p7/KfW83cK/+qIfv+62NwThNj7f/ZzW5iTUywE2faPyhgpgH6HosDv5+VDfq2kV2sXvjr2MN8+8DrthJRz986xiYyRLtp3kOVcoY+Gz+4PTU7s7vrfzrjf9TNgVen7Vi9IST3e1u7krW7mcCXaeLmiO7/2kCc9wm/9Ibc8lPGNqsb1+exXvHbI9a/T0155FmacC+w7+GA4wdObI2LybpU29YuGKaMHUC5sp83jt3JeRgttqRnjGUrpl/Y6qLqo97/XCQkDCHxg8Mmr6jzos5Zg/vDjtX76m+CZ12gaaV4txF0FvegOU4/8R9XyXlefySrht2Ob1xRT1JK3ZfSiAx1qfwtT0zYKnQuoQvxqN7DrdHxiGRQrKODZ/tbKDKujMVxEcCFHP4Zs/3JLP48le73778JilP5TSU3DKla0hqqrsczvJLSwtpcs9i7XzZPCWlcc0wemtzoHSSGS/vz9Q0Isd23LOmiIUtbUQi5gPOwVP4kjSvWlHVasiZQe1uKVgZUhBWevY0agQ/WcPj/lhM44oQA9bRlhVG1QpGiBkPf2kj4Ty0rUvrSAJSveoV+UwNepqTCpDaizsz2dgs8L/AY4Kgo8iJUfVAAAAAElFTkSuQmCC
                userId:
                  type: string
                  example: RgYM60evCyfBxbYmxWg7o0Pqhpz2
            example:
              bagItemId: 205c24f86d4b8c79201f5d4d26c7d3c4
              image: >-
                data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAl/SURBVHgB1Zt/bBTHFce/s3tnbJ+Nj/oHxaXNYWhQgohNbCN+RLKRU6VN0oIKaaK6LUZq/mijClo1SipVst30j6KmBaRGTdo/sKWgVjW0RoFGbYm4SCUmmBYnFCTUBkzS4ILt+MA+Y+7X9L29H947751373Yd8kHL7u3Nzs17897Mm7djAYcZuT3gc7vVVilEvZDwCQEfIL1SCp++nBBymP4PSIlhKWPvCKEOhcPhoWUlG4fhIAIOMBoebIWCrQrktkxBrSIghqWAX8Zkb7W72Q+bsU0BV+Q57+JYZDck9kjACwdgZUQR646Go367LKNgBSyE4JlQowP0X08oFDlQqCIKUsB49AwJLroWSvBMkhZR41rfgzzJSwHxgc11kC5bcRfAigiFw1vysQbLCnCi1yeC/8OF/55CgM4zoSl4PZ9G3dJ61NU0WKkmIGPR7uqiDfutPGRJAePRwX00Te2x8sxMeAoXPvg7rtx4RxOUWbZkFTav3o6SojL0DezFxQ9PGT67hBTRuOIRtK3dCbPQNNtVqTZ3my5vtuB45OxBCdkBC5y6dAQnzvdqSjCCBUwqJReb792OxxufgXlET5WraZepkmYKUc+fo563ZI9v/KtXE94uHiKLuTbxH01h7BpsFazAbJAlDJElrJuv3nkVkE/PX74xhN++8QM4CQv/dNsvcyrBjCUoub6knu+0Kjzzj8t/gdOwJRw+vXeeUrKDx61cJbIqgEd7MvsuWIT9fYRMdSG4TANrtvElCQ/ao6HTWQduQwXwPM9THSzCvbL36NcxEngPC8XE1PyDqFDUTk0mAwwVUFSknsxnns814n/MeBOB2xzmKOBG5ExHviu4gIkpzU54AOSYwiStRq6QpgA2E1WgE3lSTIHNQtK29luWyrMrTNDiTX8vTQFFRa7dhazf71++GQtBsbsMjz/4DEWJX4RFvJFIKM0KUnFAYoFzDgXG+Mf++ZIWATrBvWX3Y3X5fWhubIe7PO9mBlTVtWKJWBfgD67kXZXSVrBhgcM9wz3EkeB8VBZVYzUJpafEVYpS1UNHaer6syU+KluVKnOLvgsjb5JW0MUfZhVAvk9zpi3kjs5m6fB9Z44C5kAxLexqWKpKZTcSCtDGAM7hFZq701P7qZVpn9tqvqQJu6myJe3++J1Rfatmj9mbceFFesQuogUrxKvlLZGwACEErTft0/Iy7yrNDTgmeHL5TrQtfVSrflNlK5lyDV4b6ZstrPVwRgWZSsi4J2xoqqCELZ38SrzuWCtsJjkjbKxqSf6ixpdrnyBr+C4aKpqxevGaxHciUUBkba7dCEXZqp0To/8V2ExyRfibxj8YF8jHt1kP9MhkbTlCZYtQKKqq+hS3221pnW+W2oQbXJq6aFwg07fn+D9mPyfPCX1JNeci1jThcGSLImXUEQVwVNhY9wgGxv3pA1zmYJcmuEx4gpgrfNpz9riEItCg0JRQD4fgceCtMT8uTV7I+CabEArMCCcVexRAuQ6fEn9X5wycuqqrqccvLnWhZ/il9GlPQ2Qc+vuJs5hbJmaTAhRFuUfhF5VwkPuWP6Sd2RLeYnfQC2ooh7Hf67+Pue0ZA6gur2JnAGREE6W1GQ5pN1W1zvVl7Rq6+9D5PXTfxa+jxS7YhZTSZ19tWeDB8IHqjdhWsx2Vi5ZmKZXF/A3K2GX+qVrHIoP2BtoGlN2YxqJbIRhHmwI5o9BUpBgvE6wqxYy38BggieMWkEKT02Skl9SJXjcJRURK7G2yEt+ZsUCIXIdInwxExjMED36RRSrsgtZAwwpvS4HTiCxSh+9QWpemxtCdZMGcR7CqBPYiAy7ek0NXjkSDaaSmNZ2/u4sBD52vv0/OWETZEMoplpTG7yuzU12YzH6mogghjxt2EovFrrqoQVfnxOB2IzHr0xDpLr+IerW2Lq6EW+PAzXHtdmhZDYKrPkdxv7At8jNgSKHGDMFpjHxbj4t69jOURPFS2svt1srE+B/5vIPCg3eiucLhqJ+Ww3Ce+QQhE6moBsorgelJCiCcbxNvw1N4W4nTM4EaMRNqJBTEvl9WAbW4Ak7C22pYdm2kkTEchUOw8K6ZGLIuiY3CYDrctyMmFZcfvPeQz3EFQPTDAViAxSO35ymldw3dIoeUwM86pQTeeJn26xQST8CmjU/nL7yLgbMD+OiDa/h5+7NZSmWGwEYhscAr/j68f/sjbHt0K+p8K2EHbP6VrqYV8esEo+G3uyg5kvd7weB0EH/z/xUDg6dx/uK7qftPbX4M3//KLmtJ54Qu9r12EL8/dTx1e2n1UrTvaMfaNQ9o1/kSg9yV3FuYUgC/NIxGI5wctWQFLHj/8X70v/4nBINBwzLLllTj2w8/iZY161HOgU4y35/WgjiTM9M4PniSBD+GkYlRw/o8Hg82Nm1C+xPt+SgiQLnAdck9hWk/b8UKWPBXel7GiTdPwAoP1q3B52tXoLy4FLVLarR7kzNBXCNh/33tCh3D2mezPNzyBWuKkOJAlbsp9YI0TQFmreBQ36GcPf5x0L7jG5oicmG0o3ROdDIaGtwjFBhuLLo+eh0vvPgCLg8v3BYYK7AV/Kxzb1Zr0Pt+EsPwjGaEk8jYB/weCf38T567q3rdCB4fWAkr70mfMfQjvx7D7CINEjRsI7VM5p7/KfW83cK/+qIfv+62NwThNj7f/ZzW5iTUywE2faPyhgpgH6HosDv5+VDfq2kV2sXvjr2MN8+8DrthJRz986xiYyRLtp3kOVcoY+Gz+4PTU7s7vrfzrjf9TNgVen7Vi9IST3e1u7krW7mcCXaeLmiO7/2kCc9wm/9Ibc8lPGNqsb1+exXvHbI9a/T0155FmacC+w7+GA4wdObI2LybpU29YuGKaMHUC5sp83jt3JeRgttqRnjGUrpl/Y6qLqo97/XCQkDCHxg8Mmr6jzos5Zg/vDjtX76m+CZ12gaaV4txF0FvegOU4/8R9XyXlefySrht2Ob1xRT1JK3ZfSiAx1qfwtT0zYKnQuoQvxqN7DrdHxiGRQrKODZ/tbKDKujMVxEcCFHP4Zs/3JLP48le73778JilP5TSU3DKla0hqqrsczvJLSwtpcs9i7XzZPCWlcc0wemtzoHSSGS/vz9Q0Isd23LOmiIUtbUQi5gPOwVP4kjSvWlHVasiZQe1uKVgZUhBWevY0agQ/WcPj/lhM44oQA9bRlhVG1QpGiBkPf2kj4Ty0rUvrSAJSveoV+UwNepqTCpDaizsz2dgs8L/AY4Kgo8iJUfVAAAAAElFTkSuQmCC
              userId: RgYM60evCyfBxbYmxWg7o0Pqhpz2
      responses:
        '500':
          description: Internal Server Error
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Bag item image updated successfully
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Image format is not allowed or incorrect. Use base64 instead
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User has no activated trip
  /trip/bag/count:
    patch:
      tags:
        - Bag
      summary: Update bag item count
      description: ''
      operationId: updateBagItemCount
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  example: RgYM60evCyfBxbYmxWg7o0Pqhpz2
                bagItemId:
                  type: string
                  example: 205c24f86d4b8c79201f5d4d26c7d3c4
                count:
                  type: number
                  example: 2
            example:
              userId: RgYM60evCyfBxbYmxWg7o0Pqhpz2
              bagItemId: 205c24f86d4b8c79201f5d4d26c7d3c4
              count: 2
      responses:
        '500':
          description: Internal Server Error
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Bag item count has been updated successfully
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Bag item with id {BAG_ITEM_ID} is not found
  /trip/bag/delete:
    delete:
      tags:
        - Bag
      summary: Remove bag item
      description: Remove bag item
      operationId: removeBagItem
      parameters:
        - name: userId
          in: query
          schema:
            type: string
            example: RgYM60evCyfBxbYmxWg7o0Pqhpz2
        - name: bagItemId
          in: query
          schema:
            type: string
            example: 675b736ea96c83b655516b57b8600044
      responses:
        '500':
          description: Internal Server Error
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Bag item has been deleted successfully
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: [
                          "Bag item with id {BAG_ITEM_ID} is not found",
                          "User has no activated trip"]
  /trip/activity/all/{userId}:
    get:
      tags:
        - Activity
      summary: Get activities
      description: Get activities items of activated trip 
      operationId: getActivities
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
            example: RgYM60evCyfBxbYmxWg7o0Pqhpz2
      responses:
        '500':
          description: Internal Server Error
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/Activity'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: 
                    type: string
                    example: User has no activated trip
  /trip/activity/{userId}:
    post:
      tags:
        - Activity
      summary: Add activity
      description: Add Activity to active trip by userId
      operationId: addActivity
      parameters:
        - name: userId
          required: true
          in: path
          schema:
            type: string
            example: RgYM60evCyfBxbYmxWg7o0Pqhpz2
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                  example: >-
                    We need to find a perfect place for set up our camp’s and
                    where we will be protected from the angry Bears.
                heading:
                  type: string
                  example: Find a Place
            example:
              description: >-
                We need to find a perfect place for set up our camp’s and where
                we will be protected from the angry Bears.
              heading: Find a Place
      responses:
        '500':
          description: Internal Server Error
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Activity added successfully
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User has no activated trip
  /trip/activity/complete:
    patch:
      tags:
        - Activity
      summary: Set activity completed
      description: Set activity completed
      operationId: setActivityCompleted
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                activityId:
                  type: string
                  example: 0ecf3c37d251c0479a09d0d88775e2e9
                userId:
                  type: string
                  example: RgYM60evCyfBxbYmxWg7o0Pqhpz2
            example:
              activityId: 0ecf3c37d251c0479a09d0d88775e2e9
              userId: RgYM60evCyfBxbYmxWg7o0Pqhpz2
      responses:
        '500':
          description: Internal Server Error
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Activity with id {ACTIVITY_ITEM_ID} has been completed successfully
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: ["Activity item with id {ACTIVITY_ITEM_ID} is not found in activated trip", "User has no activated trip"]
  /trip/activity/delete:
    delete:
      tags:
        - Activity
      summary: Delete activity
      description: Delete activity
      operationId: deleteActivity
      parameters:
        - name: userId
          in: query
          schema:
            type: string
            example: RgYM60evCyfBxbYmxWg7o0Pqhpz2
        - name: activityId
          in: query
          schema:
            type: string
            example: 292ed90808df312625d81dac028b1b9d
      responses:
        '500':
          description: Internal Server Error
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Activity with id {ACTIVITY_ITEM_ID} has been deleted successfully
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: ["Activity item with id {ACTIVITY_ITEM_ID} is not found in activated trip", "User has no activated trip"]
  /trip/all/{userId}:
    get:
      tags:
        - Trip
      summary: Get all trips
      description: Get all trips from Camping DB
      operationId: getAllTrips
      parameters:
        - name: userId
          required: true
          in: path
          schema:
            type: string
            example: RgYM60evCyfBxbYmxWg7o0Pqhpz2
      responses:
        '500':
          description: Internal Server Error
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Trip"
  /trip/activated/{userId}:
    get:
      tags:
        - Trip
      summary: Get activated trip
      description: ''
      operationId: getActivatedTrip
      parameters:
        - name: userId
          required: true
          in: path
          schema:
            type: string
            example: RgYM60evCyfBxbYmxWg7o0Pqhpz2
      responses:
        '500':
          description: Internal Server Error
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Trip"
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: 
                    type: string
                    example: User has no activated trip
  /trip/create:
    post:
      tags:
        - Trip
      summary: Create New Trip
      description: ''
      operationId: createNewTrip
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                tripName:
                  type: string
                  example: Around the world trip
                tripPeriod:
                  type: object
                  properties:
                    endDate:
                      type: string
                      example: >-
                        Tue Dec 23 2024 11:23:26 GMT+0200 (Eastern European
                        Standard Time)
                    formatted:
                      type: string
                      example: From 23 to 23 December (1 year)
                    startDate:
                      type: string
                      example: >-
                        Tue Dec 23 2023 11:23:26 GMT+0200 (Eastern European
                        Standard Time)
                userId:
                  type: string
                  example: RgYM60evCyfBxbYmxWg7o0Pqhpz2
            example:
              tripName: Around the world trip
              tripPeriod:
                endDate: >-
                  Tue Dec 23 2024 11:23:26 GMT+0200 (Eastern European Standard
                  Time)
                formatted: From 23 to 23 December (1 year)
                startDate: >-
                  Tue Dec 23 2023 11:23:26 GMT+0200 (Eastern European Standard
                  Time)
              userId: RgYM60evCyfBxbYmxWg7o0Pqhpz2
      responses:
        '500':
          description: Internal Server Error
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Trip"
  /trip/delete:
    delete:
      tags:
        - Trip
      summary: Delete trip
      description: ''
      operationId: deleteTrip
      parameters:
        - name: userId
          in: query
          schema:
            type: string
            example: RgYM60evCyfBxbYmxWg7o0Pqhpz2
        - name: tripId
          in: query
          schema:
            type: string
            example: 292ed90808df312625d81dac028b1b9d
      responses:
        '500':
          description: Internal Server Error
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Trip deleted successfully
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Trip is not found or already removed
  /trip/complete/{userId}:
    patch:
      tags:
        - Trip
      summary: Complete trip
      description: Set Trip completed after filling initial data
      operationId: completeTrip
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
            example: RgYM60evCyfBxbYmxWg7o0Pqhpz2
      responses:
        '500':
          description: Internal Server Error
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Trip with id {TRIP_ID} completed successfully
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User has no trips which is not completed yet
  /trip/activate:
    patch:
      tags:
        - Trip
      summary: Activate trip
      description: Set activated field for given Trip and User
      operationId: activateTrip
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                tripId:
                  type: string
                  example: 63c93dbe37daeff8aa65cc98
                userId:
                  type: string
                  example: RgYM60evCyfBxbYmxWg7o0Pqhpz2
            example:
              tripId: 63c93dbe37daeff8aa65cc98
              userId: RgYM60evCyfBxbYmxWg7o0Pqhpz2
      responses:
        '500':
          description: Internal Server Error
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Trip activated successfully
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Trip is not found or already activated
  /trip/deactivate/{userId}:
    patch:
      tags:
        - Trip
      summary: Deactivate trip
      description: Turn off activated field for current Trip
      operationId: deactivateTrip
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
            example: RgYM60evCyfBxbYmxWg7o0Pqhpz2
      responses:
        '500':
          description: Internal Server Error
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Trip deactivated successfully
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User has no activated trip
  /trip/snaps/{userId}:
    get:
      tags:
        - Snap
      summary: Get trip snaps
      description: Get all user snaps for all trips
      operationId: getAllUserTripSnaps
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
            example: RgYM60evCyfBxbYmxWg7o0Pqhpz2
      responses:
        '500':
          description: Internal Server Error
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Snap"
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User has no activated trip
  /trip/snaps/create:
    post:
      tags:
        - Snap
      summary: Create trip snap
      description: ''
      operationId: createTripSnap
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                image: 
                  type: string
                  example: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAl/SURBVHgB1Zt/bBTHFce/s3tnbJ
                userId:
                  type: string
                  example: RgYM60evCyfBxbYmxWg7o0Pqhpz2
            example:
              image: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAl/SURBVHgB1Zt/bBTHFce/s3tnbJ
              userId: RgYM60evCyfBxbYmxWg7o0Pqhpz2
      responses:
        '500':
          description: Internal Server Error
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Snap"
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User has no activated trip
  /teammates/all/{userId}:
    get:
      tags:
        - Teammate
      summary: Get all user teammates of activated trip
      description: ''
      operationId: getAllUserTeammates
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
            example: RgYM60evCyfBxbYmxWg7o0Pqhpz2
      responses:
        '500':
          description: Internal Server Error
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
                  default: []
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User has no activated trip
  /teammates/add:
    post:
      tags:
        - Teammate
      summary: Add teammate to activated trip
      description: ''
      operationId: addTeammate
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  example: RgYM60evCyfBxbYmxWg7o0Pqhpz2
                teammateId:
                  type: string
                  example: 3UMKTRM6JYMPL2OP2MWZWQRKXBY2
            example:
              userId: RgYM60evCyfBxbYmxWg7o0Pqhpz2
              teammateId: J9h69v4MiSWNK6VdFUBAKWQac4e2
      responses:
        '500':
          description: Internal Server Error
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Teammate added successfully
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User has no activated trip
  /teammates/delete:
    post:
      tags:
        - Teammate
      summary: Delete teammate from activated trip
      description: ''
      operationId: deleteTeammate
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  example: RgYM60evCyfBxbYmxWg7o0Pqhpz2
                teammateId:
                  type: string
                  example: J9h69v4MiSWNK6VdFUBAKWQac4e2
            example:
              userId: RgYM60evCyfBxbYmxWg7o0Pqhpz2
              teammateId: J9h69v4MiSWNK6VdFUBAKWQac4e2
      responses:
        '500':
          description: Internal Server Error
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Teammate deleted successfully
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Teammate is not found or has been already removed
  /notification/all/{userId}:
    get:
      tags:
        - Notification
      summary: Get all user notifications
      description: ''
      operationId: getAllNotifications
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
            example: RgYM60evCyfBxbYmxWg7o0Pqhpz2
      responses:
        '500':
          description: Internal Server Error
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Notification"
  /notification/create:
    post:
      tags:
        - Notification
      summary: Create notification
      description: ''
      operationId: createNotification
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  example: RgYM60evCyfBxbYmxWg7o0Pqhpz2
                title:
                  type: string
                  example: Congratulations!
                message:
                  type: string
                  example: You recieved the welcome badge
                type:
                  type: string
                  example: trip
            example:
              userId: RgYM60evCyfBxbYmxWg7o0Pqhpz2
              title: Congratulations!
              message: You recieved the welcome badge
              type: badge
      responses:
        '500':
          description: Internal Server Error
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Notification"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Validation error some field is missing
  /notification/delete/{id}:
    delete:
      tags:
        - Notification
      summary: Delete notification
      description: ''
      operationId: deleteNotification
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            example: e8e0751f-a844-4cd6-89de-8a929eae3b8e
      responses:
        '500':
          description: Internal Server Error
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Notification has been deleted successfully
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Notification has been already deleted
  /feedback/all:
    get:
      tags:
        - Feedback
      summary: Get all feedbacks
      description: ''
      operationId: getAllFeedbacks
      responses:
        '500':
          description: Internal Server Error
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Feedback"
  /feedback/{userId}:
    get:
      tags:
        - Feedback
      summary: Get all user feedbacks
      description: ''
      operationId: getAllUserFeedbacks
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
            example: RgYM60evCyfBxbYmxWg7o0Pqhpz2
      responses:
        '500':
          description: Internal Server Error
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Feedback"
  /feedback/create:
    post:
      tags:
        - Feedback
      summary: Create feedback
      description: ''
      operationId: createFeedback
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  example: RgYM60evCyfBxbYmxWg7o0Pqhpz2
                message:
                  type: string
                  example: Write your feedback here
            example:
              userId: RgYM60evCyfBxbYmxWg7o0Pqhpz2
              message: Write your feedback here
      responses:
        '500':
          description: Internal Server Error
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Feedback"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Validation error some field is missing
  /feedback/delete/:
    delete:
      tags:
        - Feedback
      summary: Delete feedback
      description: ''
      operationId: deleteFeedback
      parameters:
        - name: userId
          in: query
          schema:
            type: string
            example: RgYM60evCyfBxbYmxWg7o0Pqhpz2
        - name: feedbackId
          in: query
          schema:
            type: string
            example: 63f8d789ada2dbd6f642a81c
      responses:
        '500':
          description: Internal Server Error
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Feedback has been deleted successfully
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Feedback is not found or has been already deleted
  
tags:
  - name: User
  - name: Trip
  - name: Bag
  - name: Activity
  - name: Notification
  - name: Teammate
  - name: Feedback
components:
  schemas:
    User:
      type: object
      properties:
        uid:
          type: string
          description: User registrated UID (autogenerated).
        fullname:
          type: string
          description: User application full name
        avatar:
          type: string
          format: bytes
          description: User avatar in base64 format
          default: "base64 avatar image"
        occupation:
          type: string
          description: User work position (profession)
        bio:
          type: string
          description: Info about user
      required: [fullname]
    Bag:
      type: object
      properties:
        id:
          type: string
          description: Bag item unique id (autogenerated)
        description:
          type: string
          description: Bag item title
        image:
          type: string
          description: Bag item user snap in base64 format
          default: "Unknown"
        count:
          type: number
          description: Amount of bag item
          default: 1
        userId:
          type: string
          description: User uid (server side)
      required: [description]
    Activity:
      type: object
      properties:
        id:
          type: string
          description: Activity unique id (autogenerated)
        heading:
          type: string
          description: Activity title
        description:
          type: string
          description: General info about activity
          default: "Unknown"
        completed:
          type: boolean
          description: Activity goal has been achieved
          default: false
        userId:
          type: string
          description: User uid (server side)
      required: [heading, description]
    Snap:
      type: object
      properties:
        _id:
          type: string
          description: Snap unique id (autogenerated)
        image:
          type: string
          description: User snap in base64 format
        userId:
          type: string
          description: User uid (server side)
      required: [image, userId]
    Trip:
      type: object
      properties:
        userId:
          type: string
          description: Trip author
        tripName:
          type: string
          description: Trip title or purpose
        locations:
          type: array
          default: []
          items: 
            "$ref": "#/components/schemas/TripLocation"
          description: Array of camping locations (from Front-end external API)
        teammates:
          type: array
          items:
            "$ref": "#/components/schemas/Teammate"
        tripPeriod:
          "$ref": "#/components/schemas/TripPeriod"
        bagItems:
          type: array
          items:
            "$ref": "#/components/schemas/Bag"
        activities:
          type: array
          items:
            "$ref": "#/components/schemas/Activity"
        completed:
          type: boolean
          default: false
          description: Trip is completed and user is ready to do activities
        activated:
          type: boolean
          default: false
          description: Trip is activated and user gets access to it
      required: [tripName, tripPeriod, userId]
    TripPeriod:
      type: object
      properties:
        startDate:
          type: string
          format: date
          description: Trip start date UTC format
        endDate:
          type: string
          format: date
          description: Trip finish date UTC format
        formatted:
          type: string
          description: Trip formatted period of start-finish dates
      required: [startDate, endDate, formatted]
    TripLocation:
      type: object
      properties:
        id:
          type: string
          description: Location item unique id (autogenerated)
        name:
          type: string
          description: Location item title
        description:
          type: string
          description: Location item description
        images:
          type: array
          items:
            type: string
          description: Location images urls
          default: []
        addresses:
          type: array
          items:
            type: object
            properties:
              postalCode:
                type: string
              city:
                type: string
              stateCode:
                type: string
          description: Location address array
          default: []
    Notification:
      type: object
      properties:
        id:
          type: string
          description: Notification unique id (autogenerated)
        title:
          type: string
          description: Notification title
        message:
          type: string
          description: Notification message
        type:
          type: string
          description: >
            Notification type (badge, info, success):
            * `badge` - user action reward
            * `info` - information about app states
            * `success` - successfull action
            * `invitation` - invitation user to trip (or any else)
          enum: 
            - badge
            - info
            - success
            - invitation
          default: success
        datetime:
          type: string
          format: date
          description: Notification datetime UTC format (autogenerated)
      required: [title, message, type]
    Teammate:
      type: object
      properties:
        userId: 
          type: string
          description: User uid
        isOnline:
          type: boolean
          description: User is online
          default: false
      required: [userId]
    Feedback:
      type: object
      properties:
        _id:
          type: string
          description: Feedback unique id (autogenerated)
        userId:
          type: string
          description: User uid
        message:
          type: string
          description: Feedback message
        createdAt:
          type: string
          format: date
          description: Feedback datetime UTC format (autogenerated)
      required: [userId, message]
    AppError:
      type: object
      properties:
        message:
          type: string
        code:
          type: number
          description: Error code to track status
